### ISSUE TITLE
Theme request: Dracula theme

### ISSUE THREAD

**Issue by comforttiger** [wavebeem/codehost#11]
not sure if you're taking requests for more themes to add, but if you are, please add [dracula theme](https://draculatheme.com/)

**Comment by wavebeem** [comment]
I'll consider it. Thus far I've only been making my own themes, but I could certainly try.

**Comment by comforttiger** [comment]
i tried adding it myself https://github.com/comforttiger/codehost/blob/main/src/themes/dracula.ts
if it's okay, i could make a pull request

**Comment by wavebeem** [comment]
yeah, go ahead and make a pull request. i'll look it over and see if i find any feedback for you. thanks!

**Comment by wavebeem** [comment]
Done https://github.com/wavebeem/codehost/pull/13
