### ISSUE TITLE
Feature request: Language specific URLs

### ISSUE THREAD

**Issue by jamesmunns** [wavebeem/codehost#2]
Hey! I use codehost all of the time, but 100% of the time I use it for highlighting Rust code. Would it be possible to have a subdomain or url path that pre-fills the language selector? Something like `rust.godbolt.org`.

Having something like `https://rust.codehost.wavebeem.com/` or `https://codehost.wavebeem.com/rust` (or really anything my browser history can remember and autofill!) would be awesome.

Thanks again for a super useful tool!

**Comment by wavebeem** [comment]
I definitely won't do subdomains, but I might do something with URLs. I'd probably do `https://codehost.wavebeem.com/?lang=rust`

I was also thinking it might be good to remember the language you picked last, since I feel like most people are gonna be highlighting the same languages a lot...

**Comment by wavebeem** [comment]
Actually I think it could be good to remember your last theme and language. I've been wanting to add more themes too I just haven't worked on the site more than a couple times.

**Comment by jamesmunns** [comment]
That would work too! I also usually change the theme, so either having it as part of a query parameter or a saved state would work perfect for me at least :)

**Comment by wavebeem** [comment]
the site now remembers your settings!

there's also a new theme (miasma), i updated the themes a bit, and fixed an issue with bold text being inherited

**Comment by jamesmunns** [comment]
Thanks @wavebeem, it works great!
