### ISSUE TITLE
GDScript syntax highlighting

### ISSUE THREAD

**Issue by exodrifter** [wavebeem/codehost#6]
it would be nice to have support for GDScript, the scripting language for the [Godot](https://godotengine.org/) game engine. It also appears that `prismjs` already has support for it as well, as `gdscript`.

As an aside, I could open a pull request to add support for it, but I won't get around to it for a while and I don't know how to build the code to test that my change actually works. It would be nice if the `README` had instructions for that.

**Comment by wavebeem** [comment]
good point about the README being incomplete

i added setup instructions

i found out the way i included languages is not supported by Prism.js, so i changed it to include every language

you can now use GDScript!
